### ISSUE TITLE
DOAJ news feed script error

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1014]
```
Traceback (most recent call last):
  File "/home/cloo/repl/production/doaj/src/doaj/portality/scripts/news.py", line 8, in <module>
    blog.read_feed()
  File "/home/cloo/repl/production/doaj/src/doaj/portality/blog.py", line 86, in read_feed
    save_entry(e)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/blog.py", line 92, in save_entry
    raise FeedError("There is more than one object with this id in the index: " + entry.id)
portality.blog.FeedError: There is more than one object with this id in the index: http://doajournals.wordpress.com/?p=509
```

cc @richard-jones @Steven-Eardley .

Not important unless new news items are not showing up (but they appear to be).

**Comment by richard-jones** [comment]
We haven't seen this recur to my knowledge, so closing off
