### ISSUE TITLE
Bug on save on test server (continuations)

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1034]
2016-05-25 13:49:43,496 - portality.core - ERROR - Exception on /admin/suggestion/3c8614f738544c36b40ec00181f858a9 [POST]
Traceback (most recent call last):
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/newrelic-2.64.0.48/newrelic/hooks/framework_flask.py", line 98, in _nr_wrapper_Flask_handle_exception_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/newrelic-2.64.0.48/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/flask_login.py", line 515, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/decorators.py", line 68, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/decorators.py", line 89, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/view/admin.py", line 269, in suggestion_page
    fc.finalise()
  File "/home/cloo/repl/test/doaj/src/doaj/portality/formcontext/formcontext.py", line 563, in finalise
    self.target.save()
  File "/home/cloo/repl/test/doaj/src/doaj/portality/models/suggestion.py", line 132, in save
    self.prep()
  File "/home/cloo/repl/test/doaj/src/doaj/portality/models/suggestion.py", line 128, in prep
    self._generate_index()
  File "/home/cloo/repl/test/doaj/src/doaj/portality/models/journal.py", line 202, in _generate_index
    cbib = self.bibjson()
  File "/home/cloo/repl/test/doaj/src/doaj/portality/models/journal.py", line 79, in bibjson
    return JournalBibJSON(bj)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/models/journal.py", line 697, in __init__
    super(JournalBibJSON, self).__init__(bibjson)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/models/bibjson.py", line 22, in __init__
    super(GenericBibJSON, self).__init__(raw=bibjson, construct_maintain_reference=True)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/lib/dataobj.py", line 289, in __init__
    self.data = construct(self.data, self._struct, self._coerce_map, silent_prune=construct_silent_prune, maintain_reference=construct_maintain_reference)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/lib/dataobj.py", line 1043, in construct
    raise DataStructureException(e.message)
DataStructureException: Cast with <function datify at 0x7f26e0c73a28> failed on

**Comment by dommitchell** [comment]
I was adding and removing issns from the edit journal form, eg: http://testdoaj.cottagelabs.com/admin/journal/0023aaeb7bda4c5ea314e8c1b830d024

I didn't click 'Allow incomplete form' which returned the usual, expected warnings. By then clicking 'Allow incomplete form' I get the http://testdoaj.cottagelabs.com/admin/journal/0023aaeb7bda4c5ea314e8c1b830d024#first_problem :
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

So it's something to do with the incomplete form messages.

**Comment by richard-jones** [comment]
Pinned this down to a bug in the datify coerce function, which is now resolved and PR submitted #1038

**Comment by dommitchell** [comment]
Tested. Works!
