### ISSUE TITLE
API retrieve journal error

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1081]
/portality.view.api_v1:retrieve_journal

portality.lib.dataobj:DataStructureException

"Cast with <function isolang at 0x7f61e449e578> failed on Spanish"

Reproduce with URL: https://doaj.org/api/v1/journals/5c09ea1bf49040ea86dbc5bcf4ecc064

```
Traceback (most recent call last):
File "/home/cloo/repl/production/doaj/bin/gunicorn", line 11, in <module>
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 198, in run
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 524, in manage_workers
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 590, in spawn_workers
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 132, in init_process
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 124, in run
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 30, in accept
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/web_transaction.py", line 738, in __iter__
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/web_transaction.py", line 1114, in __call__
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/web_transaction.py", line 1242, in _nr_wsgi_application_wrapper_
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
File "/home/cloo/repl/production/doaj/src/doaj/portality/decorators.py", line 53, in decorated_view
File "/home/cloo/repl/production/doaj/src/doaj/portality/decorators.py", line 179, in decorated_view
File "/home/cloo/repl/production/doaj/src/doaj/portality/view/api_v1.py", line 263, in retrieve_journal
File "/home/cloo/repl/production/doaj/src/doaj/portality/api/v1/crud/journals.py", line 41, in retrieve
File "/home/cloo/repl/production/doaj/src/doaj/portality/api/v1/data_objects/journal.py", line 205, in from_model
File "/home/cloo/repl/production/doaj/src/doaj/portality/api/v1/data_objects/common_journal_application.py", line 30, in from_model
File "/home/cloo/repl/production/doaj/src/doaj/portality/api/v1/data_objects/journal.py", line 200, in __init__
File "/home/cloo/repl/production/doaj/src/doaj/portality/lib/dataobj.py", line 291, in __init__
File "/home/cloo/repl/production/doaj/src/doaj/portality/lib/dataobj.py", line 1066, in construct
File "/home/cloo/repl/production/doaj/src/doaj/portality/lib/dataobj.py", line 1097, in construct
```

**Comment by emanuil-tolev** [comment]
```javascript
language: [
    "Spanish"
]
```

causes the failure (ValueError in to_isolang).

The error reporting bears a bit of improving (Cast with what failed on Spanish?).

Then we need to make sure the API does not allow anything but language codes.

Action here is to get a list of all language values which are not the ISO language codes that we use for consistency. Then decide what to do once we have the list, probably a manual mapping and data cleanup via a migration.
