### ISSUE TITLE
Certain article toc pages don't work

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1095]
Some articles don't have a title set? Or it can't be fetched? Not sure which, but we should probably not be erroring out.

e.g. https://doaj.org/article/36bf0590a8ba4b4196f9fe46dd4ec71c

```
2016-09-22 04:02:48,087 - portality.core - ERROR - Exception on /article/36bf0590a8ba4b4196f9fe46dd4ec71c [GET]
Traceback (most recent call last):
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.70.0.51/newrelic/hooks/framework_flask.py", line 98, in _nr_wrapper_Flask_handle_exception_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.70.0.51/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/view/doaj.py", line 271, in article_page
    return render_template('doaj/article.html', article=article, journal=journal)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.70.0.51/newrelic/api/function_trace.py", line 110, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/templating.py", line 125, in render_template
    context, ctx.app)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/templating.py", line 107, in _render
    rv = template.render(context)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.70.0.51/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/templates/doaj/article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/cloo/repl/production/doaj/src/doaj/portality/templates/base.html", line 5, in top-level template code
    {% block page_title %}<title>{{ app.config['SERVICE_NAME'] }}</title>{% endblock %}
  File "/home/cloo/repl/production/doaj/src/doaj/portality/templates/doaj/article.html", line 6, in block "page_title"
    {% set metatitle = metatitle + ' | ' + app.config['SERVICE_NAME'] %}
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by emanuil-tolev** [comment]
https://doaj.org/article/36bf0590a8ba4b4196f9fe46dd4ec71c

**Comment by richard-jones** [comment]
@Steven-Eardley can you take a look at this when you have a moment?

**Comment by Steven-Eardley** [comment]
That particular article is:

```json
{
"_index": "doaj",
"_type": "article",
"_id": "36bf0590a8ba4b4196f9fe46dd4ec71c",
"_version": 6,
"found": true,
"_source": {
"index": {
"publisher": [
"Elsevier"
],
"schema_subject": [
"LCC:Public aspects of medicine"
,
"DOAJ:Medicine (General)"
,
"DOAJ:Health Sciences"
,
"LCC:Medicine"
,
"LCC:Medicine (General)"
],
"license": [
"CC BY-NC-ND"
],
"classification": [
"Medicine"
,
"Medicine (General)"
,
"Health Sciences"
,
"Public aspects of medicine"
],
"classification_paths": [
"Medicine: Medicine (General)"
,
"Medicine: Public aspects of medicine"
],
"country": "Spain",
"issn": [
"0213-9111"
,
"1578-1283"
],
"schema_code": [
"LCC:RA1-1270"
,
"LCC:R5-920"
,
"LCC:R"
],
"language": [
"Spanish; Castilian"
,
"English"
],
"date": "2002-12-01T00:00:00Z",
"date_toc_fv_month": "2002-12-01T00:00:00Z",
"subject": [
"Medicine"
,
"Medicine (General)"
,
"Health Sciences"
,
"Public aspects of medicine"
]
},
"last_updated": "2016-09-07T14:46:35Z",
"created_date": "2013-08-30T03:29:47Z",
"admin": {
"in_doaj": true
},
"id": "36bf0590a8ba4b4196f9fe46dd4ec71c",
"bibjson": {
"end_page": "538",
"start_page": "537",
"journal": {
"publisher": "Elsevier",
"license": [
{
"url": "http://gacetasanitaria.org/es/open-access/",
"open_access": true,
"type": "CC BY-NC-ND",
"title": "CC BY-NC-ND"
}
],
"language": [
"EN"
,
"ES"
],
"title": "Gaceta Sanitaria",
"country": "ES",
"number": "6",
"volume": "16",
"issns": [
"0213-9111"
,
"1578-1283"
]
},
"month": "12",
"link": [
{
"url": "http://scielo.isciii.es/scielo.php?script=sci_arttext&pid=S0213-91112002000600014",
"type": "fulltext"
}
],
"year": "2002",
"identifier": [
{
"type": "pissn",
"id": "0213-9111"
}
],
"subject": [
{
"code": "R5-920",
"term": "Medicine (General)",
"scheme": "LCC"
}
,
{
"code": "R",
"term": "Medicine",
"scheme": "LCC"
}
,
{
"term": "Medicine (General)",
"scheme": "DOAJ"
}
,
{
"term": "Health Sciences",
"scheme": "DOAJ"
}
,
{
"code": "RA1-1270",
"term": "Public aspects of medicine",
"scheme": "LCC"
}
]
}
}
}
```

**Comment by Steven-Eardley** [comment]
The query for missing fields:

```json
{
    "query": {
        "filtered": {
            "filter": {
                "missing" : { "field" : "bibjson.title" }
            },
            "query": {
                "match_all": {}
            }
        }
    }
}
```

resulting total: 4723 on live. Navigating to the article page by ID sometimes gives the DOAJ error page rather than the internal error: https://doaj.org/article/214f5826bd3844879092e296323696ce

**Comment by richard-jones** [comment]
Can we have a look at the error that is being thrown on the server?

**Comment by Steven-Eardley** [comment]
Reproduced in dev:
```
127.0.0.1 - - [17/May/2017 17:23:05] "GET /article/00694aead27d42cf9bdb7b8fa19fce7c HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/steve/code/cl/doaj/src/doaj/portality/view/doaj.py", line 271, in article_page
    return render_template('doaj/article.html', article=article, journal=journal)
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/templating.py", line 125, in render_template
    context, ctx.app)
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/templating.py", line 107, in _render
    rv = template.render(context)
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/steve/code/cl/doaj/src/doaj/portality/templates/doaj/article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/steve/code/cl/doaj/src/doaj/portality/templates/base.html", line 5, in top-level template code
    {% block page_title %}<title>{{ app.config['SERVICE_NAME'] }}</title>{% endblock %}
  File "/Users/steve/code/cl/doaj/src/doaj/portality/templates/doaj/article.html", line 6, in block "page_title"
    {% set metatitle = metatitle + ' | ' + app.config['SERVICE_NAME'] %}
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

So I'll look into improving the resilience of the renderer, and perhaps we should consider removing articles without titles from the DOAJ. Many aren't in the DOAJ anyway (1777 out of 4848)

**Comment by Steven-Eardley** [comment]
@ClaraDOAJ this can be closed if you're happy with how the article page https://doaj.org/article/36bf0590a8ba4b4196f9fe46dd4ec71c looks now - i.e. it doesn't cause an error, and has an obvious placeholder where the title should be.

**Comment by ClaraDOAJ** [comment]
Thanks!
