### ISSUE TITLE
Article upload as asynchronous task

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1138]
* Refactor the upload handling code into a background task.  This may be best as a single task or as two distinct tasks, as the jobs it needs to handle are:
    * dereference any external files, provided by reference
    * validate and process uploaded or dereferenced files
* Migrate the existing file upload jobs to background jobs, for historical record, then remove the file uploads index.  Depending on exactly how we construct the jobs (whether they are one or two stage), we may not do this - question is whether the publisher UI can be built on the jobs index
* Refactor the publisher UI to point to the background jobs index, if required (see above)
* Refactor the way that file upload jobs are triggered
* Take into account the S3 file system, and its synchronisation lag/other limitations

**Comment by richard-jones** [comment]
done

**Comment by emanuil-tolev** [comment]
> Take into account the S3 file system, and its synchronisation lag/other limitations

Unfortunately this doesn't seem to work. I hooked testdoaj to my local ES and Redis (via ngrok Pro) and restarted the web app, huey main queue and huey long running. I then proceeded to run the doaj web app locally as well, but *not* running any huey locally. What should have happened:

1. I upload a file to localhost:5004. This creates an ES job and a Huey Redis job.
2. Huey tries to execute the job on doajtest.
3a. It succeeds if the file is already there.
3b. If it fails, it should add an audit message "failed to find blah.xml".
4. Once the retries are exausted, the job status should be "error". Instead, it is "processing". The status of the XML import displayed to the user (on the XML upload page) should also change to some appropriate system error. Instead, it is "pending".

Finally, at step 3 it took course 3b, i.e. it failed. The retries don't have a lot of waiting time (I suppose that's just the default 10s delay without any back-off?). As far as I can see the file did actually appear on test, but I assume it did so a little too slowly. I propose to increase the scheduling delay for this particular task to 60s (so it only starts executing 60s after the user first uploads the file, then on any retry the job is only picked up again after 60s - up to 3 times). I'll make and test that change since @richard-jones is probably busy with other things and I have the setup locally.

```
[2017-03-07 18:43:41,469] INFO:huey.consumer.Worker:Worker-1:Adding queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:43:47 3 retries to schedule
[2017-03-07 18:43:48,140] INFO:huey.consumer.Scheduler:Scheduler:Scheduling queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:43:47 3 retries for execution
[2017-03-07 18:43:50,007] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:43:47 3 retries
[2017-03-07 18:43:53,183] ERROR:huey.consumer.Worker:Worker-1:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/consumer.py", line 151, in process_task
    self.huey.execute(task)
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/api.py", line 266, in execute
    result = task.execute()
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/api.py", line 560, in execute
    return func(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/decorators.py", line 95, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 483, in ingest_articles
    BackgroundApi.execute(task)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/background.py", line 45, in execute
    background_task.run()
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 176, in run
    self._process(file_upload)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 227, in _process
    raise RetryException()
RetryException
[2017-03-07 18:43:53,435] INFO:huey.consumer.Worker:Worker-1:Re-enqueueing task db426589-9ed5-47f1-981a-6db3ca2776ed, 2 tries left
[2017-03-07 18:43:53,435] INFO:huey.consumer.Worker:Worker-1:Adding queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:44:03.183943 2 retries to schedule
[2017-03-07 18:44:03,907] INFO:huey.consumer.Scheduler:Scheduler:Scheduling queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:44:03.183943 2 retries for exe
cution
[2017-03-07 18:44:04,895] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:44:03.183943 2 retries
[2017-03-07 18:44:07,957] ERROR:huey.consumer.Worker:Worker-1:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/consumer.py", line 151, in process_task
    self.huey.execute(task)
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/api.py", line 266, in execute
    result = task.execute()
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/api.py", line 560, in execute
    return func(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/decorators.py", line 95, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 483, in ingest_articles
    BackgroundApi.execute(task)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/background.py", line 45, in execute
    background_task.run()
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 176, in run
    self._process(file_upload)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 227, in _process
    raise RetryException()
RetryException
[2017-03-07 18:44:08,206] INFO:huey.consumer.Worker:Worker-1:Re-enqueueing task db426589-9ed5-47f1-981a-6db3ca2776ed, 1 tries left
[2017-03-07 18:44:08,207] INFO:huey.consumer.Worker:Worker-1:Adding queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:44:17.957812 1 retries to schedule
[2017-03-07 18:44:17,921] INFO:huey.consumer.Scheduler:Scheduler:Scheduling queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:44:17.957812 1 retries for exe
cution
[2017-03-07 18:44:19,643] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:44:17.957812 1 retries
[2017-03-07 18:44:22,699] ERROR:huey.consumer.Worker:Worker-1:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/consumer.py", line 151, in process_task
    self.huey.execute(task)
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/api.py", line 266, in execute
    result = task.execute()
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/api.py", line 560, in execute
    return func(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/decorators.py", line 95, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 483, in ingest_articles
    BackgroundApi.execute(task)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/background.py", line 45, in execute
    background_task.run()
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 176, in run
    self._process(file_upload)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 227, in _process
    raise RetryException()
RetryException
[2017-03-07 18:44:22,978] INFO:huey.consumer.Worker:Worker-1:Re-enqueueing task db426589-9ed5-47f1-981a-6db3ca2776ed, 0 tries left
[2017-03-07 18:44:22,978] INFO:huey.consumer.Worker:Worker-1:Adding queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:44:32.701044 to schedule
[2017-03-07 18:44:32,934] INFO:huey.consumer.Scheduler:Scheduler:Scheduling queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:44:32.701044 for execution
[2017-03-07 18:44:34,165] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_ingest_articles: db426589-9ed5-47f1-981a-6db3ca2776ed @2017-03-07 18:44:32.701044
[2017-03-07 18:44:37,237] ERROR:huey.consumer.Worker:Worker-1:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/consumer.py", line 151, in process_task
    self.huey.execute(task)
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/api.py", line 266, in execute
    result = task.execute()
  File "/home/cloo/repl/test/doaj/local/lib/python2.7/site-packages/huey/api.py", line 560, in execute
    return func(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/decorators.py", line 95, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 483, in ingest_articles
    BackgroundApi.execute(task)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/background.py", line 45, in execute
    background_task.run()
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 176, in run
    self._process(file_upload)
  File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/ingestarticles.py", line 227, in _process
    raise RetryException()
RetryException
```

**Comment by emanuil-tolev** [comment]
Or, I could have misconfigured test. Just checking now.

**Comment by richard-jones** [comment]
To modify the re-try delay and attempts, you just need to update this config option

```python
HUEY_TASKS = {
    "ingest_articles" : {"retries" : 3, "retry_delay" : 10}
}
```

But you are right that there's a hole in the code when it gets to the end of processing.  When a file is not present, a RetryException is raised, which has the correct effect on the background jobs framework, but does not actually do anything to the job.

What it should actually do is:

* add an audit message to the job
* increment a counter on the job so we know how many re-tries have taken place
* check the retry count against the above configuration to find out if it is the last attempt, and sets the job status to "error".


Do you have the capacity for this?  If not, assign it over to me and I'll do it when I get the chance (which might not be for a while).

**Comment by emanuil-tolev** [comment]
> add an audit message to the job

Log why it's failed

**Comment by emanuil-tolev** [comment]
Increase huey logging levels as well, to DEBUG.

**Comment by emanuil-tolev** [comment]
We should increase number of retries on article ingests as well. I've reran a few jobs where they completed fine on the re-run, so the delay is obviously too short.

**Comment by emanuil-tolev** [comment]
There were 7 tasks stuck in processing this morning, all of them article ingests. I ran this on the live app server to attempt to clear them, and they have all completed successfully now:

```python
# $ DOAJENV=production python
from portality import models
from portality.tasks.ingestarticles import IngestArticlesBackgroundTask

jobs = models.BackgroundJob.q2obj(q='status:processing AND created_date:[2017-03-21 TO 2017-03-22]')
print len(jobs)

# if # of jobs looks ok - check background jobs tab first - then do the below
for job in jobs:
    IngestArticlesBackgroundTask.submit(job)
```

I like this, it highlights when things fail rather than the imports being left hanging and the editorial team + us having no visibility over failures.

**Comment by richard-jones** [comment]
I've now put in the extra logging and ability for the job to reach the error state in the event that it is on its last retry.

**Comment by emanuil-tolev** [comment]
Are you tracking anything else here or should we close?
