### ISSUE TITLE
OAI-PMH error

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1140]
> I download DOAJ metadata (JSON file) using oai-pmh protocol through http://email.doaj.org/c/eJwtjTsOwyAQBU8DnRG7YCAFRVLkHvw2duIYhJB8_dhSpNdMMfOyVwpy5KtHCQZQWkDQsxWA2oCYjb0B0zLX8J5CaxPwxbuotaRoCIj07LCQlY6Mk0BICpBvfhmjMXVn-Dx3HIe4AqL214k1rCL0saatCN49lZJjSB-Gj1T3EdKg2r__z0v5ARGfMD4  Usually I have no problems to finish the session but I have not been I able to finish downloading  in last weeks. Could you please help me? Is there any change or problem on the side of DOAJ?

I did find an error related to OAI-PMH in the app logs at /var/log/supervisor/doaj-production-error.log

```
2016-11-27 20:36:24,077 - portality.core - ERROR - Exception on /oai [GET]
Traceback (most recent call last):
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/view/oaipmh.py", line 59, in oaipmh
    result = list_records(dao, request.base_url, specified, **params)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/view/oaipmh.py", line 432, in list_records
    return _parameterised_list_records(dao, base_url, specified_oai_endpoint, metadata_prefix=metadata_prefix, from_date=from_date, until_date=until_date, oai_set=oai_set)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/view/oaipmh.py", line 474, in _parameterised_list_records
    decoded_set = decode_set_spec(oai_set) if oai_set is not None else None
  File "/home/cloo/repl/production/doaj/src/doaj/portality/view/oaipmh.py", line 113, in decode_set_spec
    return base64.urlsafe_b64decode(str(setspec).replace("~", "="))
  File "/usr/lib/python2.7/base64.py", line 112, in urlsafe_b64decode
    return b64decode(s, '-_')
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```

@richard-jones any ideas? I actually have to learn some more OAI-PMH for a project so happy to try to fix this, but it might take me a loong time to diagnose.

**Comment by richard-jones** [comment]
I'm confused by this, I'm afraid.  The OAI-PMH doesn't do JSON, it is an XML format, so if someone is trying to get JSON from it, they will certainly fail.

Also, when I follow that link (which has been obscured by the email service), it resolves to:

https://doaj.org/oai.article.

Which definitely won't give you anything except an error without more parameters.

So, I think that without more detail from the user about what they were doing when they encountered a problem, this will be difficult to diagnose.

**Comment by emanuil-tolev** [comment]
> I'm confused by this, I'm afraid. The OAI-PMH doesn't do JSON, it is an XML format, so if someone is trying to get JSON from it, they will certainly fail.

I'd ignore the URL and the mention of JSON in the request for help - I think the overall meaning is they were using OAI-PMH, and it failed halfway through paging through the results (using its cursor mechanism). That's why I was concerned by the Python error reported - it looks like the kind of thing that would break an OAI-PMH trawl in the middle.

I've advised @ClaraDOAJ to ask the user for a few more details on what they were trying to do. In terms of the JSON, I think what they mean is they convert the XML into JSON themselves, which is of course not relevant to us as an OAI-PMH service.

**Comment by emanuil-tolev** [comment]
They think the error might be temporary. They've come back with:

* * *

2016-12-07 17:09:16,205 : INFO : download_oaipmh:86 : MainProcess : download_oaipmh(MainProcess) : PROGRESS: at record #110000
Traceback (most recent call last):
  File "./download_oaipmh.py", line 117, in <module>
    download_oaipmh(base_url, output, prefix, sets)
  File "./download_oaipmh.py", line 84, in download_oaipmh
    for recno, rec in enumerate(records):
  File "/home/hostickova/.virtualenvs/ef/lib/python2.6/site-packages/oaipmh/client.py", line 335, in ResumptionListGenerator
    result, token = nextBatch(token)
  File "/home/hostickova/.virtualenvs/ef/lib/python2.6/site-packages/oaipmh/client.py", line 178, in nextBatch
    resumptionToken=token)
  File "/home/hostickova/.virtualenvs/ef/lib/python2.6/site-packages/oaipmh/client.py", line 269, in makeRequestErrorHandling
    xml = self.makeRequest(**kw)
  File "/home/hostickova/.virtualenvs/ef/lib/python2.6/site-packages/oaipmh/client.py", line 316, in makeRequest
    return retrieveFromUrlWaiting(request)
  File "/home/hostickova/.virtualenvs/ef/lib/python2.6/site-packages/oaipmh/client.py", line 343, in retrieveFromUrlWaiting
    f = urllib2.urlopen(request)
  File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 1178, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.6/urllib2.py", line 1145, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

* * *

We can close if you like, since a temporary network error is not something we can fix, and they should finish their harvesting soon. Unless it turns out we always time out on that record or something, but then that's a permanent error.

I'd still be interested in what that error is in my original post, but it's not something that somebody has actually complained about, and many people are presumably still getting all their OAI-PMH from us just fine. So the priority is quite low.

**Comment by richard-jones** [comment]
Ok, I'm going to close this since we haven't heard any more.
