### ISSUE TITLE
Intermittent build failure related to article cleanup tests

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1218]
```
======================================================================
ERROR: test_03_prepall (test_article_cleanup_sync.TestArticleCleanupSync)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/rof/src/github.com/DOAJ/doaj/doajtest/unit/test_article_cleanup_sync.py", line 133, in test_03_prepall
assert a1u.bibjson().data.get("journal") == a1.bibjson().data.get("journal")
AttributeError: 'NoneType' object has no attribute 'bibjson'
-------------------- >> begin captured stdout << ---------------------
account 200
bulk_upload 200
bulk_reapplication 200
background_job 200
provenance 200
lock 200
journal 200
cache 200
upload 200
journal_history 200
article_history 200
lcc 200
suggestion 200
toc 200
article 200
news 200
editor_group 200

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 273 tests in 564.473s

FAILED (errors=1)
```

**Comment by emanuil-tolev** [comment]
Further intemittent failure:

```
======================================================================
FAIL: test_02_write (test_article_cleanup_sync.TestArticleCleanupSync)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/rof/src/github.com/DOAJ/doaj/doajtest/unit/test_article_cleanup_sync.py", line 64, in test_02_write
assert models.Journal.count() == 1
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
account 200
bulk_upload 200
bulk_reapplication 200
background_job 200
provenance 200
lock 200
journal 200
cache 200
upload 200
journal_history 200
article_history 200
lcc 200
suggestion 200
toc 200
article 200
news 200
editor_group 200

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 273 tests in 566.977s

FAILED (failures=1)
```

**Comment by emanuil-tolev** [comment]
This happens in about 70-80% of my builds.

**Comment by emanuil-tolev** [comment]
Another failure in the same file. Probably all those are for the same reason?

```
======================================================================
FAIL: test_03_prepall (test_article_cleanup_sync.TestArticleCleanupSync)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/rof/src/github.com/DOAJ/doaj/doajtest/unit/test_article_cleanup_sync.py", line 134, in test_03_prepall
assert datetime.strptime(a1u.last_updated, "%Y-%m-%dT%H:%M:%SZ") > datetime.strptime(a1.last_updated, "%Y-%m-%dT%H:%M:%SZ")
AssertionError: 
```

**Comment by Steven-Eardley** [comment]
Increased sleeps by a second (50%) each to give the task more time to run - since I can't persuade my laptop or codeship to fail with the new delay, can you let me know if it's fixed on yours?

**Comment by emanuil-tolev** [comment]
Some more from today:

```
======================================================================
FAIL: test_02_write (test_article_cleanup_sync.TestArticleCleanupSync)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/rof/src/github.com/DOAJ/doaj/doajtest/unit/test_article_cleanup_sync.py", line 64, in test_02_write
assert models.Journal.count() == 1
AssertionError: 
```

**Comment by Steven-Eardley** [comment]
:-(

**Comment by Steven-Eardley** [comment]
could that be an old branch?

**Comment by emanuil-tolev** [comment]
In develop itself? https://app.codeship.com/projects/49473/builds/23623849 (it's a hotfix back-merge of the tagged `production` commit of a hotfix I merged).

**Comment by Steven-Eardley** [comment]
That'll be a no then.
