### ISSUE TITLE
API internal server error on journal GET

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1223]
First 10 results of query https://doaj.org/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22journal%22%7D%7D%2C%7B%22term%22%3A%7B%22index.has_apc.exact%22%3A%22Yes%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22*%5C%5C%3A*%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D#.WKVY6xIrLXH used as input to the DOAJ API v1:

 1 ; https://doaj.org/toc/1932-6246 ; https://doaj.org/api/v1/journals/0023aaeb7bda4c5ea314e8c1b830d024 ; HTTP 500 (Internal Server Error)
 2 ; https://doaj.org/toc/1110-0362 ; https://doaj.org/api/v1/journals/008e9712ea7d4bd98104d89b5128953a ; HTTP 500 (Internal Server Error)
 3 ; https://doaj.org/toc/2460-7916 ; https://doaj.org/api/v1/journals/00ab07bee006472491791e157008e421 ; HTTP 500 (Internal Server Error)
 4 ; https://doaj.org/toc/2455-6890 ; https://doaj.org/api/v1/journals/01229b2437fb4c13b692520215ab4f07 ; HTTP 500 (Internal Server Error) 
 5 ; https://doaj.org/toc/2095-9869 ; https://doaj.org/api/v1/journals/01351203015d45f7915f5209f196bce6 ; HTTP 500 (Internal Server Error) 
 6 ; https://doaj.org/toc/2110-5820 ; https://doaj.org/api/v1/journals/014850470c6045b497d64abad23a9ccb ; HTTP 200 (OK)
 7 ; https://doaj.org/toc/1001-9014 ; https://doaj.org/api/v1/journals/014e077538f54ed7bb257eef26329b54 ; HTTP 500 (Internal Server Error)
 8 ; https://doaj.org/toc/2090-701X ; https://doaj.org/api/v1/journals/015f4cd6015048fe9068fd988882f867 ; HTTP 500 (Internal Server Error)
 9 ; https://doaj.org/toc/1177-889X ; https://doaj.org/api/v1/journals/0172cf70305845508fb05fe7bcae115f ; HTTP 500 (Internal Server Error)
10 ; https://doaj.org/toc/2049-3258 ; https://doaj.org/api/v1/journals/0186d00072d64108b58976acbb0b34d5 ; HTTP 200 (OK)

**Comment by emanuil-tolev** [comment]
Seems to be the only error for all those 8 error URLs:

```
/home/cloo/repl/production/doaj/src/doaj/portality/lib/isolang.py:6: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if key in [r.lower() for r in row]:
2017-02-16 09:24:13,880 - portality.core - ERROR - Exception on /api/v1/journals/0172cf70305845508fb05fe7bcae115f [GET]
Traceback (most recent call last):
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.78.0.57/newrelic/hooks/framework_flask.py", line 103, in _nr_wrapper_Flask_handle_exception_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.78.0.57/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/decorators.py", line 53, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/decorators.py", line 179, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/view/api_v1.py", line 263, in retrieve_journal
    return jsonify_data_object(JournalsCrudApi.retrieve(journal_id, current_user))
  File "/home/cloo/repl/production/doaj/src/doaj/portality/api/v1/crud/journals.py", line 41, in retrieve
    return OutgoingJournal.from_model(j)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/api/v1/data_objects/journal.py", line 205, in from_model
    return super(OutgoingJournal, cls).from_model(jm)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/api/v1/data_objects/common_journal_application.py", line 30, in from_model
    return cls(d)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/api/v1/data_objects/journal.py", line 200, in __init__
    super(OutgoingJournal, self).__init__(raw, struct=JOURNAL_STRUCT, construct_silent_prune=True, expose_data=True)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/lib/dataobj.py", line 303, in __init__
    self.data = construct(self.data, self._struct, self._coerce_map, silent_prune=construct_silent_prune, maintain_reference=construct_maintain_reference)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/lib/dataobj.py", line 1099, in construct
    beneath = construct(val, instructions, coerce=coerce, context=context + field_name + ".", silent_prune=silent_prune)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/lib/dataobj.py", line 1099, in construct
    beneath = construct(val, instructions, coerce=coerce, context=context + field_name + ".", silent_prune=silent_prune)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/lib/dataobj.py", line 1078, in construct
    raise DataStructureException(u"Schema exception at {a}, {b}".format(a=field_name, b=e.message))
DataStructureException: Schema exception at url, Cast with <function to_url at 0x7f82c94e55f0> failed on
```

Seems to be relatively simple.

We also need to enhance the tests - we have really good coverage of the API code itself, so if this is a problem with the data handling layer and there is a hole in the coverage there, we definitely need to fix that :). Indeed I would've thought even the API tests might have caught something like this.

**Comment by ClaraDOAJ** [comment]
Any developments here?

**Comment by Steven-Eardley** [comment]
Journal 1 (minus admin section) is below; there are a few empty string URLs.

```json
{
  "index": {
    "oa_statement_url": "http://docs.lib.purdue.edu/jps/policies.html",
    "classification": [
      "Consciousness. Cognition"
    ],
    "has_seal": "No",
    "asciiunpunctitle": "Journal of Problem Solving",
    "subject": [
      "Consciousness. Cognition",
      "psychology",
      "computational models",
      "problem solving",
      "psychology of problem solving",
      "artificial systems"
    ],
    "has_editor": "Yes",
    "title": [
      "Journal of Problem Solving"
    ],
    "classification_paths": [
      "Philosophy. Psychology. Religion: Psychology: Consciousness. Cognition"
    ],
    "has_editor_group": "Yes",
    "aims_scope_url": "http://docs.lib.purdue.edu/jps/aimsandscope.html",
    "provider_ac": "berkeley electronic press",
    "unpunctitle": "Journal of Problem Solving",
    "has_apc": "Yes",
    "publisher_ac": "purdue university press",
    "schema_code": [
      "LCC:BF309-499"
    ],
    "author_instructions_url": "http://docs.lib.purdue.edu/jps/policies.html",
    "continued": "No",
    "editorial_board_url": "http://docs.lib.purdue.edu/jps/editorialboard.html",
    "publisher": [
      "Purdue University Press"
    ],
    "schema_subject": [
      "LCC:Consciousness. Cognition"
    ],
    "license": [
      "CC BY-NC-ND"
    ],
    "language": [
      "English"
    ],
    "country": "United States",
    "issn": [
      "1932-6246"
    ],
    "homepage_url": "http://docs.lib.purdue.edu/jps/"
  },
  "last_updated": "2017-02-28T13:04:44Z",
  "last_manual_update": "2016-10-24T11:56:39Z",
  "last_reapplication": "2016-10-24T11:56:15Z",
  "created_date": "2009-08-03T17:32:25Z",
  "id": "0023aaeb7bda4c5ea314e8c1b830d024",
  "bibjson": {
    "format": [
      "PDF"
    ],
    "plagiarism_detection": {
      "detection": false,
      "url": ""
    },
    "allows_fulltext_indexing": true,
    "apc_url": "http://docs.lib.purdue.edu/jps/policies.html",
    "archiving_policy": {
      "url": "http://docs.lib.purdue.edu/jps/about.html",
      "known": [
        "CLOCKSS",
        "Portico"
      ]
    },
    "active": true,
    "persistent_identifier_scheme": [
      "DOI"
    ],
    "link": [
      {
        "url": "http://docs.lib.purdue.edu/jps/",
        "type": "homepage"
      },
      {
        "url": "http://docs.lib.purdue.edu/jps/editorialboard.html",
        "type": "editorial_board"
      },
      {
        "url": "http://docs.lib.purdue.edu/jps/aimsandscope.html",
        "type": "aims_scope"
      },
      {
        "url": "http://docs.lib.purdue.edu/jps/policies.html",
        "type": "author_instructions"
      },
      {
        "url": "http://docs.lib.purdue.edu/jps/policies.html",
        "type": "oa_statement"
      }
    ],
    "oa_start": {
      "year": 2006
    },
    "keywords": [
      "psychology of problem solving",
      "computational models",
      "problem solving",
      "psychology",
      "artificial systems"
    ],
    "apc": {
      "currency": "USD",
      "average_price": 500
    },
    "editorial_review": {
      "process": "Double blind peer review",
      "url": "http://docs.lib.purdue.edu/jps/policies.html"
    },
    "author_copyright": {
      "url": "",
      "copyright": "False"
    },
    "subject": [
      {
        "code": "BF309-499",
        "term": "Consciousness. Cognition",
        "scheme": "LCC"
      }
    ],
    "deposit_policy": [
      "Sherpa/Romeo"
    ],
    "license": [
      {
        "open_access": true,
        "embedded": false,
        "title": "CC BY-NC-ND",
        "url": "http://docs.lib.purdue.edu/jps/policies.html",
        "NC": true,
        "ND": true,
        "embedded_example_url": "",
        "SA": false,
        "type": "CC BY-NC-ND",
        "BY": true
      }
    ],
    "language": [
      "EN"
    ],
    "article_statistics": {
      "url": "http://docs.lib.purdue.edu/jps/",
      "statistics": true
    },
    "title": "Journal of Problem Solving",
    "country": "US",
    "publication_time": 17,
    "publisher": "Purdue University Press",
    "submission_charges_url": "http://docs.lib.purdue.edu/jps/policies.html",
    "author_publishing_rights": {
      "url": "",
      "publishing_rights": "False"
    },
    "provider": "Berkeley Electronic Press",
    "identifier": [
      {
        "type": "eissn",
        "id": "1932-6246"
      }
    ]
  }
}
```

**Comment by ClaraDOAJ** [comment]
Please translate...:D

**Comment by emanuil-tolev** [comment]
> Please translate...:D

I think it's just troubleshooting technical info for other developers to help solve the problem.

**Comment by ClaraDOAJ** [comment]
Hello @emanuil-tolev Any solutions here? Our users are asking.

Thanks!

**Comment by emanuil-tolev** [comment]
Will try to get to this asap. @richard-jones does this look familiar?

> DataStructureException: Schema exception at url, Cast with <function to_url at 0x7f82c94e55f0> failed on

**Comment by richard-jones** [comment]
We'd need to look at the details of the cast function, but it's evidently failing to convert something.  It ought to tell you where in the datastructure after "failed on ...."

As @Steven-Eardley notes, there are some empty string urls, so this might be a bug in that to_url function.

**Comment by richard-jones** [comment]
@emanuil-tolev - was this done last week as planned?

**Comment by ClaraDOAJ** [comment]
Hello, I have been approached by the publishers again, we need to sort this out asap. They have been waiting for such a long time now....

**Comment by emanuil-tolev** [comment]
They have indeed. I'll take another look before our meeting tomorrow.

**Comment by emanuil-tolev** [comment]
@ClaraDOAJ Explanation:

> This is fixed on live. It was caused by us translating data from the internal DOAJ data model to the public API. The case was slightly complicated by faulty error reporting. Our apologies for the long wait, the affected journals should now be retrievable via the Journal CRUD API. Please let us know if you encounter any more server errors trying to retrieve journal or article data, we should be able to fix them faster now.

**Comment by ClaraDOAJ** [comment]
Thank you very much, I really appreciate it.
Best
Clara

**Comment by ClaraDOAJ** [comment]
I have informed the publisher. I will leave the issue open until they confirm the fix works.
Many thanks!
