### ISSUE TITLE
Testing Bulk edit - error 1

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1326]
1. Changing Editora da Pontifícia Universidade Católica do Rio Grande do Sul (EDIPUCRS) to  Pontifícia Universidade Católica do Rio Grande do Sul
 
Your bulk edit request has been submitted and queued for execution.
14 journals have been queued for edit.
You can see your request here in the background jobs interface (opens new tab).
You will get an email when your request has been processed; this could take anything from a few minutes to a few hours.
dismiss
 
In background jobs:
 
journal_bulk_edit by alejandra status: error
Job ID: 0ac31ce0bcc04510b40bc09609825da8
Job Created: 19 Jun 2017 at 14:22
Job Last Updated: 19 Jun 2017 at 14:22
 
More Information
Parameters:
journal_bulk_edit__ids -- 1f35bd71581447da995ff1d7c12d0d7d, a28b5f47bc8f4159a6dbbb7d350544f7, 7fbd75aa5dec49348b836d3aafbf0dd1, cc05ae5bb359489aad6cbf6eefd1bd5d, 6f3540f4f2254d7d909ea4b3accbce7c, 0402c3d950174e498b777e88a7c7f52b, 239e9294416745bca042e2eb5f0d5a53, 20df01213f724eaa99b3fba458cc82d2, 6db9ddd154b046c9bbe1a28aad76bdbc, f4e54ac7705b48cd83430171ff172430, 5a2cffb30b47496db7f335ae38687dee, c9b3211beec54e8b92c8ce201ac1892e, 580b1b52c0014fac9d3b5313ae0bc54b, ac84b7487b69464491ce6d973053a5c7
journal_bulk_edit__replacement_metadata -- {"publisher": "Pontif\u00edcia Universidade Cat\u00f3lica do Rio Grande do Sul"}
Reference:
journal_bulk_edit__selection_query -- {"query": {"filtered": {"filter": {"bool": {"must": [{"term": {"index.publisher.exact": "Editora da Pontif\u00edcia Universidade Cat\u00f3lica do Rio Grande do Sul (EDIPUCRS)"}}, {"term": {"_type": "journal"}}]}}, "query": {"query_string": {"query": "Pontif\u00edcia Universidade Cat\u00f3lica", "default_operator": "AND"}}}}}
Audit Messages:
2017-06-19T14:22:12.150301Z -- Job Started
2017-06-19T14:22:12.178299Z -- Error in Job Run
2017-06-19T14:22:12.179849Z -- Caught in job runner during run: Traceback (most recent call last): File "/home/cloo/repl/test/doaj/src/doaj/portality/background.py", line 47, in execute background_task.run() File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/journal_bulk_edit.py", line 114, in run job.add_audit_message(u"Setting {f} to {x} for journal {y}".format(f=k, x=str(v), y=journal_id)) UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 6: ordinal not in range(128) 
2017-06-19T14:22:12.180333Z -- Job Run Completed
2017-06-19T14:22:12.180861Z -- Cleanup Started
2017-06-19T14:22:12.302264Z -- Job Cleanup Completed
2017-06-19T14:22:12.302856Z -- Job Finished

**Comment by Steven-Eardley** [comment]
Looks like a double encoding issue, so a bug with the audit message code.

**Comment by richard-jones** [comment]
unnecessary call to str() in .format(), by the looks of it.  format() is robust, as far as I can tell, so it will stringify/unicode whatever we give it.
