### ISSUE TITLE
Test bulk edit - error 2

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1327]
2. Selecting 224 Redalyc journals for the Seal
Your bulk edit request has been submitted and queued for execution.
224 journals have been queued for edit.
You can see your request here in the background jobs interface (opens new tab).
You will get an email when your request has been processed; this could take anything from a few minutes to a few hours.
dismiss
 
journal_bulk_edit by alejandra status: error
Job ID: ed403102101b427a895686c064a6d7e9
Job Created: 19 Jun 2017 at 14:58
Job Last Updated: 19 Jun 2017 at 14:59
 
More Information
Parameters:
journal_bulk_edit__ids -- 188d0458092b4bf681e10cee469bb6f3, 23ee6f4e1d594fa99bf4d873dee9d54a, 2b5deddcec5943dab2db7413ba131af6, 0aa427437b854e469a31feae26ea8fc0, 12ecbea307d54705865e4324a9715a71, 3a8d719e7ca84ac9b202094765a88fcf, 42009345740e45be8804cfc0e3801115, 42e08baada354af98036eaf86171c277, 4e38301dee2f40a78bf02af045f8b0ab, 4e9e6c0afc124a2f9177c1d50df8e216, 510816c2bbed4646b37fbdd30cddc382, 5568a6eef83041fe8cb822401131e4d9, 63315c54538c4409af3ea74f0b7a3ac1, e2dd493d09b346689284d391cf47ce8b, e9574ba83a4e4b2da0e6f5368195b684, eea57a10504a48d9aae3db513456489d, a5c591abd2354ca097b2284055c1986e, aa8c6539c9394f3d846e017038978305, ae9f611224b8415a9e4559c6e1d0d982, 9abd589610b4407086ebf16b03376ada, 78d5225c994a4105b2c85dc9ca83b66e, 81f1fcf4b5c246cfbe4c60a971790359, 89297c4c412043b383682f8694963a48, 930470d83b274e56a361497e0276fad0, d6865259f19c4af880ec9a7795e3fb35, dd355a03874e4e69a6518e9b150c79c9, de46d25a09c94ef0904fabf6da0f6e22, 6bfd26b16fb04671b84a68f408479416, b6e062f98fb847cf90e0602f20a2f29a, bac2dc6d7d4f45d3a6f200d9b0689381, cb06ee80f50240208a4a3fabfa050180, ccdd37428d694726b10e4b765df1acbf, 0fea6b152a4d4860be00d496212ca035, 103c32d3816d448fa7cd70e52351f8ba, 163ac62572844a1099e7dd635b9bfa84, 300d6d52823c4bc5b69739cdc15d4389, 31355db1af4f4d028d398d553cd2de4f, 400bcf0207254f9ba0bf313a2e3272cc, 22dc23d70a0d460d9ee961c2d8ba9473, 2a74d59820a14bc48838f8519a90de79, 011aaa19ef454f07bd994a936140d6b6, 0392a005218d4b1aa8d6b82c5404ee1e, 576bdba9c77b4621849d58360107aeb1, 58b0ff15dfa84e54a7536c680920f5eb, 5d00415b168145ae8da631828b364d93, 60ba864baac64a08bdb310fc36fcb921, 65a7d890213f45cb8c1c498ea103f0a3, 6686a7cfad9c402294af19b97f674265, bdbf2df7739d4421ad5d09b8ada81cdd, bdca8e1f6b0d40458a0d7e3338be6e67, be93876f761744c9895a47469bbe809f, c2525497476248868e5d89e50a7b03d4, c573cd900cc44477bff5ad33820a8b65, c9de9bd6423c4cc38d3b4ad583464ea9, d1660cecc5b240518158679520b1f356, a5a70470105d49db8562202607270df1, adea10e6529f4815a360246093592661, b0fe50437ff542c3a27cda557eb07a30, b74e1c6cc00e4dbc81098813a72d0084, d46b161bca554c03af1473b64cc91857, dd8f4f5ae65f45e88ef6266355183a69, 4168c067422d430bae68f00e4266c9b1, 430bbbadbf52452da33124367107a5bb, 4d1315d78bca47119651b6b73d648c84, 6b11d16dbffd418d865825e7e689805e, 6f95a3c136314b90ad92c3ffae9de2c1, 7828beef6a0b40ee9a16393a897ecc84, 889768ae68c34f02853356b947b3ca81, 8f79704fd6f940e88318637994b864ad, 949b6a43e468484a8d34d5f748896466, 7b4744326b304d5aad4f318eafed9d32, 7d3a709237454129873a55d68e8b4efc, 81dcb4fce5c044fd86e5c60f50e72224, 82a807b5d38e44e3a42a128d23784701, 9f8bb1fe91f846b7b6ff547b752d213d, a30b54ce95794395af7bc58a2fa6ebf5, e781f119cdab4088a6fc7b8b95686e00, ecd9d2cb0e734ce7a388881c980d3127, edb0e3d224b8449881fb125725f9b837, f36f6e5fca1f46c58ec0dc8c557153b6, f443ff0c77434fd5a1f1b13689da6cdf, f61dce00c5664e05936ccfa338898478, fed5674d8ca64289867deb8e1b769976, 2f93018e7bdf41e69308fc6d16342984, 310ac5c1130d4dcdb242ad8eb9f27418, 3fdf2fbcfac04399b901551b8aa5688f, 174e5b34691f4916beef19d0f2a07b0f, 1ee08dffc7d94e4780a082fa60f825f4, 240a72461a8749329b6f17d8b9d7e228, 2502fae193dc440abc4ab08d5e2cae64, 2e497f8c8bdb4f0ea21da62a97a51694, eef859114aa043d3a8935f890c45ba87, f1c3640d11ec43ab905ac057830f6abd, f6c5eadf27b74238bac4617913ae5213, fa4b6947389b47d8abfd3ddd7d22977e, 478388092ecd45bd9c4d3fdb85895f67, 478a162c51304beabc47a3bbef3d3537, 546e1b59973a44bdb23acb29941cb760, 5f457a9baee8472fac167f128286b42e, d734a1d3df2c4738b9b758309e23f6bf, d8531041707e41b68b4f218ef0e75e61, e36abc8a9f2b471f92d6a6271ac7522a, c545bfe06af148429acf817b50d77fe2, c6c7c52eb4ff4f858eb9c3cc131b2d96, a3081582d32c4a05b4496915c9da1c37, 7c78a6455a9147ef87706741f4f4fb9e, 7d489e70c2db42dfaa8f78a60250ff49, 7d9a0fe62bdf45d9b2c568ed1fa91c49, 800c5bf25b10438ebda569a16f9d463b, 8106b0adbee14b879a2d33fd59c07b27, 8825034069f74d63bbb1efa9cce48b52, 8d02d89db28a4bb0ae46be37bc286dde, 925a221fb85c427b8bb34908f3a19970, a5e06e1824dc4229995b5b5915ce65d3, b1962456e911463b9cff50b105d67b96, b1e27da1247a48bfa1c80c2df681d03f, b3c327c3dbeb478184437729b613dad3, b8a2b961572842a48d4210ea7a572695, b97029c0aea742efb7385d954504b76c, bb3f2e54098744e9812d7e8ea3052ace, 1351c26957984c57a7ca3a97bd8eb896, 145d9166623548bfb1f6136b0822e98a, 1f9761d71c4e4df09d18d5e531ba6369, 32715e61309f4c3d82f44a9958108ce3, 365c401e8fff43839a346b1e894ce807, 38555cda4b124fb391446f69a5f58e3b, 03c5642f69bc4664962ef5ccde10e36f, 11dbe19b98b344f59137c6f3f4469c0f, 8135e96a24a24a889d166bb01225581d, 86b231e247b244bc8c3cdc3b042d05b7, 6e5bdac6821a4e02b80d7d25fa424ced, 6ee0a059f72c46c2a90f1bc9dc6eeacf, 7216158ae137438f9c8367704df967f1, 75be2773a4b84dd2b4f51041eb4e83cb, 77cab4c8890a425b9688399d0c8e2255, f10236bc7c4f461d9e12caf501d662d1, 5acf8a381a144f388f86f5bf60ddf76c, 5e72fe2b8ff04ee2adc6c3dba173d437, e36284da0e8343959cbdf64b0ad683b8, 9859f483eb33461aa02783421b4838d0, a33aae349c6342268c2e7f1e3e559b3e, 3d9731ec29ba4fe4a6da4c241e954b27, 40be8e05fd654d649576f9086cf4f05f, b1d32a5e5caa46cc8c648669061e8546, d49f0d225b5545a3be503bc8357f5575, dcf830fed0b54106a9ddabbb3d53d001, df434068e13340bf89e8642f91c94cc5, b466646f5488435397dc71352337788e, ba66fd80ab9b483a8b69f7b93e25b5c7, c102d41075084973834c7e1c19cdcb71, c2843ec8ef144f25b02343e4e292a9a9, caf56719c6764bdba80648a74ec6d098, cd2d3b6bf7864985ad36a5cac6ec996f, cef6a90aeb8f484eb96774adcb48d543, cf55c3c040a94617a58900b092157b70, 1ebbbad9f0d346c8b1ebf361a62136ce, 2caadec484f2467bad8fed85f685d902, 2cd22b02ce6c444587f5f0070f1e96c9, 315868e7bbf14246996c74913f7ff418, 38830b48d4dd4c63adc744ad26ada6bc, 45c127d75bb343cda37d86db86f3968a, 4f9d54b9e0d7447d9b4e786008eb3f82, 52835d21d8334e3d94d169b66ec1f5df, 58ba7f14730840b6bcd09fed49260a73, a804dcbada054a96a1f9401b2e0b560d, aacc255c1b6a4abda9f3cd8ce25961a5, ac4e7e26955844bc8fe99832b27a2b31, b7eaf47c09ff41a094f80ab13b5b6ed1, be2efab8afd243bfaabe36dd4a4f95eb, c25332a092b14500b13d607ae325fc14, cbb64c8482ce429984e1493f633190b9, cbf0d2e590f94dac896a95d1c1a1abf2, ccbea8e5afe348c39f2c3b7d083e2e01, cd208884637742aba39676d0c0870cda, 7a88e00533e741a987ee1ccd9d35a237, 7f485a6bd6994f52b6ea561d364fa67d, 86915d99bf0b47d08bf57805dd398642, d4208b16620143b98703f941acbba103, da31d65f77784cbe92d563c74c3e915a, 891286bf2a4d48aa85ce46c7ae078ba7, 8e273c5aad224d4eb5c6eb573551e919, 8ff017b4797641fd88787ada51b17779, 5f81318d25fa4d64ba0e22ea4b09a19c, 61465dbda82848a58221a981ef741922, 7013ac259a0646d58ff70561962addc8, 979624282a1347888a99366261bfdd7f, e4b4390242a64f80a0760a0fd32122ec, eab65a5bab5f48989e048dde72f090fd, f2312c6181954b76b7fd032102babaf8, 0b03de79504f4461bbc21f15dc5548b3, 12cd8490b7bb46439d43da72c5487d0b, 1ae4d1db9bf2408f88a0e67ca32fc92e, 2208b36d1d374a8a871ade0b1b495627, 3a871351639a47d689d9a8f00f79cc0d, 3aad5eed5c5747b58c0f00b845fc1581, 3b4fd0623c3a47a0976530ec54cd64c2, 043f4b5918fe457c81560eb7974670fa, 49d292aad55f440a8493f1a5054c498a, 4c132b4c9db141ecb272f27fb0566fea, b2d5a278b71f4c1f93b33d30343317dc, bbed2a34b50241f7ab9c00ce1da8327a, c17eb61d2459414abb077118ee01a687, c7bdaa54538b490890b1dd689a226a70, cdf2548d0ca34fffb942aedafabb7038, 60c028c5f1604c47ba6e118f1584f031, 98ce2cc8dde5465b96f1f0f260a74446, 9cff9b22cd8a4450bdcf78d960003e23, 9fbc7383d97d49f2ba8b8024e198a568, a27ddf2c5e894998b6f6fed4f8176cee, a2929213c9b04937b41d40b67090ddba, 891da713eec7429c8ebd5917ef8c28d7, 95b6570badeb406ca25846577837f3da, 7ca830a09625401a876745040430f272, 83b2a219f1f546228f07d0f2b0eae2c3, 8656d694a3c042bba9f4923eca0efc22, 877b848779dc48109467552c456944ce, d2d02c187ed74029ac62e0b973a7f37d, d50d5e1a15f74ccbb8ccb4098fbbd465, e22863e0769a48288413c1919a6f1df3, e49729bf418b455287cffda38c6090f5, e9b27f2a12fe4f658abb666a852d96a8, eecb98eb13fd45e28dbbde385675906a, f8842047bebb4f54976d6adb5314ca2a, fd43b9df4a5c45febfab14aa8d894165
journal_bulk_edit__replacement_metadata -- {"doaj_seal": true}
Reference:
journal_bulk_edit__selection_query -- {"query": {"filtered": {"filter": {"bool": {"must": [{"term": {"_type": "journal"}}, {"term": {"bibjson.provider.exact": "Redalyc"}}]}}, "query": {"match_all": {}}}}}
Audit Messages:
2017-06-19T14:59:07.878772Z -- Job Started
2017-06-19T14:59:07.913802Z -- Setting doaj_seal to True for journal 188d0458092b4bf681e10cee469bb6f3
2017-06-19T14:59:08.005396Z -- Setting doaj_seal to True for journal 23ee6f4e1d594fa99bf4d873dee9d54a
2017-06-19T14:59:08.078630Z -- Setting doaj_seal to True for journal 2b5deddcec5943dab2db7413ba131af6
2017-06-19T14:59:08.115334Z -- Setting doaj_seal to True for journal 0aa427437b854e469a31feae26ea8fc0
2017-06-19T14:59:08.162227Z -- Setting doaj_seal to True for journal 12ecbea307d54705865e4324a9715a71
2017-06-19T14:59:08.229751Z -- Setting doaj_seal to True for journal 3a8d719e7ca84ac9b202094765a88fcf
2017-06-19T14:59:08.270147Z -- Setting doaj_seal to True for journal 42009345740e45be8804cfc0e3801115
2017-06-19T14:59:08.304306Z -- Setting doaj_seal to True for journal 42e08baada354af98036eaf86171c277
2017-06-19T14:59:08.342509Z -- Setting doaj_seal to True for journal 4e38301dee2f40a78bf02af045f8b0ab
2017-06-19T14:59:08.392197Z -- Setting doaj_seal to True for journal 4e9e6c0afc124a2f9177c1d50df8e216
2017-06-19T14:59:08.438919Z -- Setting doaj_seal to True for journal 510816c2bbed4646b37fbdd30cddc382
2017-06-19T14:59:08.475713Z -- Setting doaj_seal to True for journal 5568a6eef83041fe8cb822401131e4d9
2017-06-19T14:59:08.513205Z -- Setting doaj_seal to True for journal 63315c54538c4409af3ea74f0b7a3ac1
2017-06-19T14:59:08.547625Z -- Setting doaj_seal to True for journal e2dd493d09b346689284d391cf47ce8b
2017-06-19T14:59:08.594738Z -- Setting doaj_seal to True for journal e9574ba83a4e4b2da0e6f5368195b684
2017-06-19T14:59:08.635384Z -- Setting doaj_seal to True for journal eea57a10504a48d9aae3db513456489d
2017-06-19T14:59:08.670858Z -- Setting doaj_seal to True for journal a5c591abd2354ca097b2284055c1986e
2017-06-19T14:59:08.708612Z -- Setting doaj_seal to True for journal aa8c6539c9394f3d846e017038978305
2017-06-19T14:59:08.746341Z -- Setting doaj_seal to True for journal ae9f611224b8415a9e4559c6e1d0d982
2017-06-19T14:59:08.782473Z -- Setting doaj_seal to True for journal 9abd589610b4407086ebf16b03376ada
2017-06-19T14:59:08.822200Z -- Setting doaj_seal to True for journal 78d5225c994a4105b2c85dc9ca83b66e
2017-06-19T14:59:08.882727Z -- Setting doaj_seal to True for journal 81f1fcf4b5c246cfbe4c60a971790359
2017-06-19T14:59:08.961525Z -- Setting doaj_seal to True for journal 89297c4c412043b383682f8694963a48
2017-06-19T14:59:09.025091Z -- Setting doaj_seal to True for journal 930470d83b274e56a361497e0276fad0
2017-06-19T14:59:09.058702Z -- Setting doaj_seal to True for journal d6865259f19c4af880ec9a7795e3fb35
2017-06-19T14:59:09.115165Z -- Setting doaj_seal to True for journal dd355a03874e4e69a6518e9b150c79c9
2017-06-19T14:59:09.182853Z -- Setting doaj_seal to True for journal de46d25a09c94ef0904fabf6da0f6e22
2017-06-19T14:59:09.230308Z -- Setting doaj_seal to True for journal 6bfd26b16fb04671b84a68f408479416
2017-06-19T14:59:09.289495Z -- Setting doaj_seal to True for journal b6e062f98fb847cf90e0602f20a2f29a
2017-06-19T14:59:09.387910Z -- Setting doaj_seal to True for journal bac2dc6d7d4f45d3a6f200d9b0689381
2017-06-19T14:59:09.470920Z -- Setting doaj_seal to True for journal cb06ee80f50240208a4a3fabfa050180
2017-06-19T14:59:09.561302Z -- Setting doaj_seal to True for journal ccdd37428d694726b10e4b765df1acbf
2017-06-19T14:59:09.634774Z -- Setting doaj_seal to True for journal 0fea6b152a4d4860be00d496212ca035
2017-06-19T14:59:09.700585Z -- Setting doaj_seal to True for journal 103c32d3816d448fa7cd70e52351f8ba
2017-06-19T14:59:09.746505Z -- Setting doaj_seal to True for journal 163ac62572844a1099e7dd635b9bfa84
2017-06-19T14:59:09.789607Z -- Setting doaj_seal to True for journal 300d6d52823c4bc5b69739cdc15d4389
2017-06-19T14:59:09.865043Z -- Setting doaj_seal to True for journal 31355db1af4f4d028d398d553cd2de4f
2017-06-19T14:59:09.964692Z -- Setting doaj_seal to True for journal 400bcf0207254f9ba0bf313a2e3272cc
2017-06-19T14:59:10.003597Z -- Setting doaj_seal to True for journal 22dc23d70a0d460d9ee961c2d8ba9473
2017-06-19T14:59:10.039849Z -- Setting doaj_seal to True for journal 2a74d59820a14bc48838f8519a90de79
2017-06-19T14:59:10.078464Z -- Setting doaj_seal to True for journal 011aaa19ef454f07bd994a936140d6b6
2017-06-19T14:59:10.140536Z -- Setting doaj_seal to True for journal 0392a005218d4b1aa8d6b82c5404ee1e
2017-06-19T14:59:10.180886Z -- Setting doaj_seal to True for journal 576bdba9c77b4621849d58360107aeb1
2017-06-19T14:59:10.222629Z -- Setting doaj_seal to True for journal 58b0ff15dfa84e54a7536c680920f5eb
2017-06-19T14:59:10.264594Z -- Setting doaj_seal to True for journal 5d00415b168145ae8da631828b364d93
2017-06-19T14:59:10.307879Z -- Setting doaj_seal to True for journal 60ba864baac64a08bdb310fc36fcb921
2017-06-19T14:59:10.370533Z -- Setting doaj_seal to True for journal 65a7d890213f45cb8c1c498ea103f0a3
2017-06-19T14:59:10.451659Z -- Setting doaj_seal to True for journal 6686a7cfad9c402294af19b97f674265
2017-06-19T14:59:10.485912Z -- Setting doaj_seal to True for journal bdbf2df7739d4421ad5d09b8ada81cdd
2017-06-19T14:59:10.529806Z -- Setting doaj_seal to True for journal bdca8e1f6b0d40458a0d7e3338be6e67
2017-06-19T14:59:10.593163Z -- Setting doaj_seal to True for journal be93876f761744c9895a47469bbe809f
2017-06-19T14:59:10.643523Z -- Setting doaj_seal to True for journal c2525497476248868e5d89e50a7b03d4
2017-06-19T14:59:10.687441Z -- Setting doaj_seal to True for journal c573cd900cc44477bff5ad33820a8b65
2017-06-19T14:59:10.721309Z -- Setting doaj_seal to True for journal c9de9bd6423c4cc38d3b4ad583464ea9
2017-06-19T14:59:10.753374Z -- Setting doaj_seal to True for journal d1660cecc5b240518158679520b1f356
2017-06-19T14:59:10.794705Z -- Setting doaj_seal to True for journal a5a70470105d49db8562202607270df1
2017-06-19T14:59:10.860862Z -- Setting doaj_seal to True for journal adea10e6529f4815a360246093592661
2017-06-19T14:59:10.906540Z -- Setting doaj_seal to True for journal b0fe50437ff542c3a27cda557eb07a30
2017-06-19T14:59:10.941675Z -- Setting doaj_seal to True for journal b74e1c6cc00e4dbc81098813a72d0084
2017-06-19T14:59:10.985951Z -- Setting doaj_seal to True for journal d46b161bca554c03af1473b64cc91857
2017-06-19T14:59:11.061979Z -- Setting doaj_seal to True for journal dd8f4f5ae65f45e88ef6266355183a69
2017-06-19T14:59:11.110854Z -- Setting doaj_seal to True for journal 4168c067422d430bae68f00e4266c9b1
2017-06-19T14:59:11.113796Z -- Error in Job Run
2017-06-19T14:59:11.114632Z -- Caught in job runner during run: Traceback (most recent call last): File "/home/cloo/repl/test/doaj/src/doaj/portality/background.py", line 47, in execute background_task.run() File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/journal_bulk_edit.py", line 141, in run if fc.validate(): File "/home/cloo/repl/test/doaj/src/doaj/portality/formcontext/formcontext.py", line 1374, in validate self.pre_validate() File "/home/cloo/repl/test/doaj/src/doaj/portality/formcontext/formcontext.py", line 1317, in pre_validate self._validate_editor_field() File "/home/cloo/repl/test/doaj/src/doaj/portality/formcontext/formcontext.py", line 327, in _validate_editor_field raise FormContextException("Editor '{0}' not found in editor group '{1}'".format(editor, editor_group_name)) FormContextException: Editor 'cafe' not found in editor group 'Portuguese3' 
2017-06-19T14:59:11.114906Z -- Job Run Completed
2017-06-19T14:59:11.115160Z -- Cleanup Started
2017-06-19T14:59:12.388870Z -- Job Cleanup Completed
2017-06-19T14:59:12.389271Z -- Job Finished

**Comment by richard-jones** [comment]
I've added some code to the journal bulk edit feature which looks out for invalid editors, and strips them from the metadata.  This makes it functionally equivalent to the application form for an individual item.
