### ISSUE TITLE
Email exceptions showing 500 page

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1467]
The control flow for the form context emails in https://github.com/DOAJ/doaj/blob/develop/portality/formcontext/emails.py relies on exception raising to display alerts on the edit forms. From an email thread, the Internal Server Error page is displayed due to emails.

We shouldn't be seeing that 500 page, only the alerts in https://github.com/DOAJ/doaj/blob/develop/portality/formcontext/formcontext.py

e.g. from recent error:

```
doaj-production-error.log:2017-12-12 15:02:57,996 - portality.core - ERROR - Exception on /admin/suggestion/a762f18e697a4a6ba28bebf80c678ada [POST]
doaj-production-error.log-Traceback (most recent call last):
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
doaj-production-error.log-    response = self.full_dispatch_request()
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
doaj-production-error.log-    rv = self.handle_user_exception(e)
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
doaj-production-error.log-    return cors_after_request(app.make_response(f(*args, **kwargs)))
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic/hooks/framework_flask.py", line 108, in _nr_wrapper_Flask_handle_exception_
doaj-production-error.log-    return wrapped(*args, **kwargs)
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
doaj-production-error.log-    rv = self.dispatch_request()
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
doaj-production-error.log-    return self.view_functions[rule.endpoint](**req.view_args)
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic/hooks/framework_flask.py", line 45, in _nr_wrapper_handler_
doaj-production-error.log-    return wrapped(*args, **kwargs)
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask_login.py", line 515, in decorated_view
doaj-production-error.log-    return fn(*args, **kwargs)
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/src/doaj/portality/decorators.py", line 68, in decorated_view
doaj-production-error.log-    return fn(*args, **kwargs)
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/src/doaj/portality/decorators.py", line 95, in decorated_view
doaj-production-error.log-    return fn(*args, **kwargs)
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/src/doaj/portality/view/admin.py", line 302, in suggestion_page
doaj-production-error.log-    fc.finalise()
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/src/doaj/portality/formcontext/formcontext.py", line 700, in finalise
doaj-production-error.log-    raise e
doaj-production-error.log-AttributeError: 'NoneType' object has no attribute 'email'
doaj-production-error.log-Traceback (most recent call last):
doaj-production-error.log-  File "/home/cloo/repl/production/doaj/src/doaj/portality/error_handler.py", line 36, in emit
doaj-production-error.log-    smtp.sendmail(self.fromaddr, self.toaddrs, msg)
doaj-production-error.log-  File "/usr/lib/python2.7/smtplib.py", line 736, in sendmail
doaj-production-error.log-    (code, resp) = self.data(msg)
doaj-production-error.log-  File "/usr/lib/python2.7/smtplib.py", line 497, in data
doaj-production-error.log-    raise SMTPDataError(code, repl)
doaj-production-error.log-SMTPDataError: (550, '5.4.5 Daily user sending quota exceeded. x13sm18257479wre.65 - gsmtp')
```

**Comment by richard-jones** [comment]
We need to do two things here:

1. Align error email sending with the rest of the email sending in the app

2. Add a None check to the associate_editor email routine, so it doesn't trigger an error anyway

**Comment by richard-jones** [comment]
Let's make sure that this is rationalised with the app_email module, and also that it is turned off in production

**Comment by Steven-Eardley** [comment]
Error emails have been turned off.
