### ISSUE TITLE
read_news is failing in production

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1479]
Since 4th Dec 2017.
```
2018-01-04T13:34:47.595116Z -- Caught in job runner during run: Traceback (most recent call last): File "/home/cloo/repl/production/doaj/src/doaj/portality/background.py", line 47, in execute background_task.run()
File "/home/cloo/repl/production/doaj/src/doaj/portality/tasks/read_news.py", line 19, in run blog.read_feed()
File "/home/cloo/repl/production/doaj/src/doaj/portality/blog.py", line 91, in read_feed save_entry(e) File "/home/cloo/repl/production/doaj/src/doaj/portality/blog.py", line 97, in save_entry raise FeedError("There is more than one object with this id in the index: " + entry.id)
FeedError: There is more than one object with this id in the index: http://blog.doaj.org/?p=1681 
```

The first earliest error is ```FeedError: There is more than one object with this id in the index: http://blog.doaj.org/?p=1873```

Since then it's been ```http://blog.doaj.org/?p=1681```

We probably just need to delete these duplicate entries.

**Comment by Steven-Eardley** [comment]
The following query can be used on the ```news/_search``` endpoint to find the duplicates causing these errors:

```json
{
    "query": {
        "match_all": {}
    },
    "size": 100,
    "aggregations": {
        "same_rem_id": {
            "terms": {
                "field": "remote_id.exact"
            }
        }
    }
}
```
