### ISSUE TITLE
bulk edit error

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1480]
Job ID:  0bda40abd8904d168af037326b278a19

Can someone take a quick look and establish if we are doing something wrong? We are trying to bulk accept applications from 1 publisher.

http://bit.ly/2CQSHpS

**Comment by Steven-Eardley** [comment]
The error from the task log is:

```
Caught in job runner during run: 
Traceback (most recent call last): 
File "/home/cloo/repl/production/doaj/src/doaj/portality/background.py", line 47, in execute background_task.run() 
File "/home/cloo/repl/production/doaj/src/doaj/portality/tasks/suggestion_bulk_edit.py", line 113, in run fc.finalise() 
File "/home/cloo/repl/production/doaj/src/doaj/portality/formcontext/formcontext.py", line 626, in finalise jurl = url_for("doaj.toc", identifier=j.toc_id) 
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/helpers.py", line 361, in url_for return appctx.app.handle_url_build_error(error, endpoint, values) 
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/helpers.py", line 354, in url_for force_external=external) 
File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1607, in build raise BuildError(endpoint, values, method) 
BuildError: ('doaj.toc', {'identifier': u'0081-6485'}, None) 
```

The error happens in the formcontext when we save the application, then generate a URL to produce an alert on the admin edit form. Since this is a background task, it may not have access to ```url_for()``` on the running app so it's failing. Then again, why haven't we seen this before?

In any case, the alert isn't relevant to the background task so we can add a workaround to suppress the error.

**Comment by greboun** [comment]
thanks
Sounds logical to me

TOM


Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support
