### ISSUE TITLE
Single article landing page

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#540]
* includes embedded metadata
* links to OpenURL work

**Comment by Steven-Eardley** [comment]
@dommitchell You can now review the article page changes via the search on doaj.cottagelabs.com

**Comment by emanuil-tolev** [comment]
@Steven-Eardley Some articles seem to be causing an error, like https://doaj.cottagelabs.com/article/cc3a7008c7484cc68c319ca28358e937

This is the error
```
[2015-03-21 17:30:32 +0000] [16533] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    for item in respiter:
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/api/web_transaction.py", line 711, in __iter__
    for item in self.generator:
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/api/web_transaction.py", line 1087, in __call__
    self.start_response)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/api/web_transaction.py", line 1215, in _nr_wsgi_application_wrapper_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/framework_flask.py", line 98, in _nr_wrapper_Flask_handle_exception_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/framework_flask.py", line 98, in _nr_wrapper_Flask_handle_exception_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/apps/doaj/src/doaj/portality/view/doaj.py", line 176, in article_page
    return render_template('doaj/article.html', article=article, countries=countries_dict)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/api/function_trace.py", line 110, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/templating.py", line 125, in render_template
    context, ctx.app)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/templating.py", line 107, in _render
    rv = template.render(context)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cloo/repl/apps/doaj/src/doaj/portality/templates/doaj/article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/cloo/repl/apps/doaj/src/doaj/portality/templates/base.html", line 18, in top-level template code
    {% block content %}{% endblock %}
  File "/home/cloo/repl/apps/doaj/src/doaj/portality/templates/doaj/article.html", line 68, in block "content"
    <a href={{ "/toc/" + article.bibjson().get_identifiers(idtype='pissn')[0] or article.bibjson().get_identifiers(idtype='eissn')[0]}}>{{ article.bibjson().journal_title }}</a></p>
UndefinedError: list object has no element 0
```

**Comment by dommitchell** [comment]
Dom to do today.

**Comment by dommitchell** [comment]
Here's our thoughts on this:

![article_long](https://cloud.githubusercontent.com/assets/5955396/6784113/07fbdcc6-d17e-11e4-9321-07bdf4747df8.jpg)

**Comment by richard-jones** [comment]
@Steven-Eardley - see the layout code in templates/doaj/toc.html for help in doing this

**Comment by richard-jones** [comment]
Done a full implementation for next PR

**Comment by dommitchell** [comment]
Some changes needed to bring this in line with the updated version of the journal landing page:

- [ ] remove the licensing logo, top right.
- [ ] change ABSTRACT to Abstract
- [ ] can we do anything about the layout of the authors? Is it possible to put each author on a new line? For example: https://doaj.cottagelabs.com/article/f8a2d8709a2540018b866c70f39c2bba
Maria Dezio (Postgraduate School of Orthodontics, School of Orthodontics, Orthodontic Department, Faculty of Dentistry, University of Cagliari, Cagliari, Sardinia, Italy),
Alessandra Piras (School of Orthodontics, Orthodontic Department, Faculty of Dentistry, University of Cagliari, Cagliari, Sardinia, Italy),
Livio Gallottini (Freelance Professional, Rome, Italy),
Gloria Denotti (School of Dentistry and Postgraduate School of Orthodontics, University of Cagliari, Cagliari, Sardinia, Italy) 
- [ ] Precede journal title with 'Journal Title:' in bold. For example: 'Journal Title: Palliative Care : Research and Treatment'
- [ ] Add 'ISSN' to ISSN. For example: ISSN 1178-2242 (Print)

**Comment by richard-jones** [comment]
Changes made for next PR

**Comment by dommitchell** [comment]
Perfect!
