### ISSUE TITLE
New toc page gives 500 response when no volumes found

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#628]
Via the facetview search or openurl endpoint, generating a TOC for a journal with no volume information causes a 500 response and therefore the 'Internal Server Error' page.

```bash
127.0.0.1 - - [28/Mar/2015 15:37:42] "GET /doaj?func=openurl&issn=18581447&genre=journal HTTP/1.1" 301 -
Legacy OpenURL 0.1 request: http://localhost:5004/openurl?genre=journal&issn=18581447&func=openurl
127.0.0.1 - - [28/Mar/2015 15:37:42] "GET /openurl?genre=journal&issn=18581447&func=openurl HTTP/1.1" 301 -
OpenURL 1.0 request: http://localhost:5004/openurl?url_ctx_fmt=info:ofi/fmt:kev:mtx:ctx&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&url_ver=Z39.88-2004&rft.func=openurl&rft.issn=18581447&rft.genre=journal
Query from OpenURL: {'query': {'bool': {'should': [{'term': {'index.issn.exact': u'1858-1447'}}]}}}
127.0.0.1 - - [28/Mar/2015 15:37:42] "GET /openurl?url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ver=Z39.88-2004&rft.func=openurl&rft.issn=18581447&rft.genre=journal HTTP/1.1" 302 -
2015-03-28 15:37:42,396 - portality.core - ERROR - Exception on /toc/51740b3ea80a4b34b79ad4a6840a8f6d [GET]
Traceback (most recent call last):
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/steve/code/cl/doaj/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/steve/code/cl/doaj/src/doaj/portality/view/doaj.py", line 189, in toc
    return render_template('doaj/toc.html', journal=journal, articles=articles, volumes=all_volumes, current_volume=volume, issues=all_issues, current_issue=issue, countries=countries_dict)
UnboundLocalError: local variable 'all_issues' referenced before assignment
127.0.0.1 - - [28/Mar/2015 15:37:42] "GET /toc/51740b3ea80a4b34b79ad4a6840a8f6d HTTP/1.1" 500 -
```

**Comment by markmacgillivray** [comment]
Ok I'll look at that, I didn't think of journals without toc.

Mark

**Comment by markmacgillivray** [comment]
Fixed by the change Richard already made to routes.
