### ISSUE TITLE
Some pages returning Internal Server error

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#668]
https://testdoaj.cottagelabs.com/toc/eba9a5a55bf244159e97c286586dd769
https://testdoaj.cottagelabs.com/toc/50b494579f1343b0a2d42934455d26a5

**Comment by richard-jones** [comment]
The first one works for me.

The second gives me an Internal Server Error.

@emanuil-tolev - can you see what's happening in the logs?

**Comment by emanuil-tolev** [comment]
(fyi You can always check the latest live and test errors in Newrelic too.)

https://rpm.newrelic.com/accounts/526071/applications/13026512/traced_errors

exceptions:UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

```
Traceback (most recent call last):
File "/home/cloo/repl/apps/doaj/bin/gunicorn", line 11, in <module>
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 174, in run
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 540, in spawn_workers
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 124, in init_process
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 119, in run
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 66, in run_for_one
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 30, in accept
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/web_transaction.py", line 711, in __iter__
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/web_transaction.py", line 1087, in __call__
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/web_transaction.py", line 1215, in _nr_wsgi_application_wrapper_
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
File "/home/cloo/repl/apps/doaj/src/doaj/portality/view/doaj.py", line 212, in toc
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/function_trace.py", line 110, in literal_wrapper
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/templating.py", line 125, in render_template
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/flask/templating.py", line 107, in _render
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
File "/home/cloo/repl/apps/doaj/src/doaj/portality/templates/doaj/toc.html", line 1, in top-level template code
File "/home/cloo/repl/apps/doaj/src/doaj/portality/templates/base.html", line 84, in top-level template code
File "/home/cloo/repl/apps/doaj/src/doaj/portality/templates/doaj/toc.html", line 113, in block "content"
File "/home/cloo/repl/apps/doaj/local/lib/python2.7/site-packages/jinja2/filters.py", line 329, in do_join
```

1:35pm looks like exactly 17 min ago, when you made the comment above, so def. looks like your error. And it looks like the right page too!

**Comment by richard-jones** [comment]
Ah damnit - unicode error.  Not sure why that would happen in this position, though!

**Comment by richard-jones** [comment]
@richard-jones to update bibjson.language_name() to give back unicode data

**Comment by richard-jones** [comment]
Done for next PR
