### ISSUE TITLE
sitemap errors

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#677]
```
Traceback (most recent call last):
  File "/home/cloo/repl/apps/doaj/src/doaj/portality/scripts/sitemap.py", line 50, in <module>
    toc_loc = base_url + "toc/" + j["id"]
TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by emanuil-tolev** [comment]
this has changed with the most recent work on ToCs done to 

```
Traceback (most recent call last):
  File "/home/cloo/repl/apps/doaj/src/doaj/portality/scripts/sitemap.py", line 50, in <module>
    toc_loc = base_url + "toc/" + j.toc_id
AttributeError: 'dict' object has no attribute 'toc_id'
```

looks like the journal isn't a model object in that loop? not sure what's going on, will prob. fix after release today/tomorrow though

**Comment by richard-jones** [comment]
fixed
