### ISSUE TITLE
500 Internal Server Error when adding a new editor

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#912]
Rikard experienced a problem adding a user liana to editorial group Spanish4.

I found what I believe is the right error in the logs:

```
2015-10-27 11:40:20,805 - portality.core - ERROR - Exception on /admin/editor_group/5381055a44fa49e79578700a1ece49ab [POST]
Traceback (most recent call last):
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/framework_flask.py", line 98, in _nr_wrapper_Flask_handle_exception_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/flask_login.py", line 515, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/decorators.py", line 67, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/decorators.py", line 88, in decorated_view
    return fn(*args, **kwargs)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/view/admin.py", line 297, in editor_group
    if form.validate():
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 200, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 220, in _run_validation_chain
    validator(form, self)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/view/forms.py", line 979, in __call__
    if acc.has_role(self.role) and not acc.is_super:
AttributeError: 'NoneType' object has no attribute 'has_role'
```

Not quite sure what's going on, but leaving here to investigate later - it seems that "liana" does not exist as an account. Not sure, can you assign accounts that do not yet exist to editorial groups? Probably not. But we should give an appropriate error message instead of 500 if that's so.

FYI @greboun

**Comment by emanuil-tolev** [comment]
Apologies to Rikard, I seem to have munged that up in my mind. liana does exist. I have also, good news, found the problem. The issue is that another editor, "luisa", is part of this Editor Group but her account's actually been deleted (see https://doaj.org/account/luisa - Not Found!). This presents the system with a dilemma - you're asking it to make "Associate Editors: christian, luisa, marsolh, verabaceta, juliana, kostas, liana" the new Spanish4 group. But luisa does not exist and it can't perform any checks on an account that does not exist. I think we need to do 2 things: 

- when a user is deleted remove them from editorial groups
- fix that part of the system so it gives an error that one of the associate editor accounts does not exist if this somehow happens again

I have now removed luisa manually from Spanish4. Could Rikard try adding liana again? It should work now. @greboun

**Comment by richard-jones** [comment]
Propose to move the fixes to a tnm task - @greboun , @dommitchell can you confirm?

**Comment by dommitchell** [comment]
Close this one for now.
